### ISSUE TITLE
The crash when install GT TC and ExU

### ISSUE THREAD

**Issue by AustenXiyue** [Robotia/ExtraUtilities#9]
[When I install Gregtech, Extra Utilities and Thaumcraft, the game will be crash
I can't install these three mods in same time, I can only install two of them in same time, like GT and TC or GT and ExU or TC and ExU, but if I install like GT and TC and ExU in same time, the game will "bomb"!
I'm trying to find the way to solve this problem in google, but there are no answer
Mod version:
GregTech-5.09.29.jar
Extra Utilities-1.2.12.jar
IndustrialCraft-2-2.2.820-experimental.jar
ThaumCraft-1.7.10-4.2.3.5.jar
Baubles-1.7.10-1.0.1.10.jar

The crash_reports:
[crash-2018-03-16_20.20.32-client.txt](https://github.com/sameer/ExtraUtilities/files/1821224/crash-2018-03-16_20.20.32-client.txt)

**Comment by sameer** [comment]
Looks like a Thaumcraft issue with Extra utilities -- not exactly sure why.

On Mar 16, 2018 22:23, "Austen48" <notifications@github.com> wrote:

[When I install Gregtech, Extra Utilities and Thaumcraft, the game will be
crash
I can't install these three mods in same time, I can only install two of
them in same time, like GT and TC or GT and ExU or TC and ExU, but if I
install like GT and TC and ExU in same time, the game will "bomb"!
I'm trying to find the way to solve this problem in google, but there are
no answer
Mod version:
GregTech-5.09.29.jar
Extra Utilities-1.2.12.jar
IndustrialCraft-2-2.2.820-experimental.jar
ThaumCraft-1.7.10-4.2.3.5.jar
Baubles-1.7.10-1.0.1.10.jar

The crash_reports:
crash-2018-03-16_20.20.32-client.txt
<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsameer%2FExtraUtilities%2Ffiles%2F1821224%2Fcrash-2018-03-16_20.20.32-client.txt&data=02%7C01%7Csameer.puri%40mail-service-3-mx.vanderbilt.edu%7Ccda78d1bbff84a14680408d58bb68295%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636568538347846700&sdata=EmLtGbUeYkRdzh%2BC49cUPL7Y%2BKj1mNSC1tF8Hv4l1vk%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsameer%2FExtraUtilities%2Fissues%2F9&data=02%7C01%7Csameer.puri%40mail-service-3-mx.vanderbilt.edu%7Ccda78d1bbff84a14680408d58bb68295%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636568538347846700&sdata=uc2BuOllFEjikVU2Lp6HJUuy2PIdYcSccji2Cuq6kPM%3D&reserved=0>,
or mute the thread
<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKlUCFa3voMYMvf_41F4kqVcLh6nILwOks5tfIHJgaJpZM4Supha&data=02%7C01%7Csameer.puri%40mail-service-3-mx.vanderbilt.edu%7Ccda78d1bbff84a14680408d58bb68295%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636568538347846700&sdata=bjj1GZWQOVs%2FhdXL20du7%2Fhv7jasSLdUzZXaXNBK13A%3D&reserved=0>
.

**Comment by AustenXiyue** [comment]
How to fix this problem? To change the config?

**Comment by AustenXiyue** [comment]
I'm trying to update every mod to fix this problem, but game still not work

**Comment by AustenXiyue** [comment]
Oh, I was solve this problem, change the Thaumcraft's name to "ATHaumcraft-1.7.10-4.2.3.5.jar", May the ExU's name should change to other
![6](https://user-images.githubusercontent.com/25553318/37622052-eb6c01f0-2b7d-11e8-8d71-99a584dc6cd3.PNG)
This problem was solved, this issue can be close.
